### ISSUE TITLE
샘플에서 스크립트 오류가 납니다. 

### ISSUE THREAD

**Issue by easylogic** [lab89/tagular#1]
https://lab89.github.io/sample/tagular-list

여기 페이지에서 버튼 3개 중에  앞에 2개를 클릭한 이후에  마지막 버튼을 클릭하면  아래와 같은 에러가 나옵니다. 

<img width="533" alt="스크린샷 2021-01-11 오후 6 04 02" src="https://user-images.githubusercontent.com/591983/104162153-6935cc80-5437-11eb-824e-6cbe6aa86aa2.png">

https://github.com/lab89/tagular/blob/925d9ef16b446b70336884301ed8074bf3f5111f/src/reader/reader.ts#L142

**Comment by lab89** [comment]
헛 파일이 예전걸로 가 있는 것 같습니다. 이슈 이런거 생전 처음 받아보는데,, 감사합니다. 수정하고 말씀 드리겠습니다.

**Comment by lab89** [comment]
> https://lab89.github.io/sample/tagular-list
> 
> 여기 페이지에서 버튼 3개 중에 앞에 2개를 클릭한 이후에 마지막 버튼을 클릭하면 아래와 같은 에러가 나옵니다.
> 
> <img alt="스크린샷 2021-01-11 오후 6 04 02" width="533" src="https://user-images.githubusercontent.com/591983/104162153-6935cc80-5437-11eb-824e-6cbe6aa86aa2.png">
> 
> https://github.com/lab89/tagular/blob/925d9ef16b446b70336884301ed8074bf3f5111f/src/reader/reader.ts#L142

수정하여 올려 뒀습니다. js파일은 반영되는데 5분정도 걸리더라고요. ㅎㅎ 이슈 제기 감사드립니다!

**Comment by lab89** [comment]
응답 해 주신걸루 알고 이 이슈는 닫도록 하겠습니다. 다시한번 감사드립니다 ~ !
